version: "3.9"

services:
  web:
    image: mayank035/movies-recommendation:latest
    container_name: movie_recommendation_app
    ports:
      - "8501:8501"
    environment:
      PYTHONUNBUFFERED: "1"
      MONGO_URI: "mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27019/moviesdb"
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: movie_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: moviesdb
    volumes:
      - mongo_data:/data/db
    ports:
      - "27019:27017"

volumes:
  mongo_data: {}

